apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: sk-rohit-portfolio
  labels:
    app: sk-rohit-portfolio
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sk-rohit-portfolio
  template:
    metadata:
      labels:
        app: sk-rohit-portfolio
    spec:
      containers:
        - name: portfolio
          image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
